# Generated by Django 4.0.3 on 2022-07-28 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 8, 42, 10, 64094, tzinfo=utc)),
        ),
    ]
