<<<<<<< Updated upstream:migrations/0002_alter_attendancesession_start_time.py
# Generated by Django 4.0.3 on 2022-07-28 08:42
=======
# Generated by Django 4.0.3 on 2022-07-28 10:56
>>>>>>> Stashed changes:migrations/0003_alter_attendancesession_start_time.py

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
<<<<<<< Updated upstream:migrations/0002_alter_attendancesession_start_time.py
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 8, 42, 10, 64094, tzinfo=utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 28, 10, 56, 38, 12261, tzinfo=utc)),
>>>>>>> Stashed changes:migrations/0003_alter_attendancesession_start_time.py
        ),
    ]
