# Generated by Django 4.0.3 on 2022-07-16 14:42

import datetime
from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSessionStatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecordTypes',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='stafftitle',
            name='unique_title',
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 16, 14, 42, 48, 126899, tzinfo=utc)),
        ),
        migrations.AddConstraint(
            model_name='stafftitle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper(django.db.models.functions.text.Replace('title', django.db.models.expressions.Value('.'), django.db.models.expressions.Value(''))), name='conflicting_title_abbreviation'),
        ),
        migrations.AddConstraint(
            model_name='stafftitle',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('title_full'), name='unique_title'),
        ),
    ]
