# Generated by Django 4.0.3 on 2022-07-26 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_admissionstatus_attendancesessionstatus_eventtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 12, 31, 17, 469942, tzinfo=utc)),
        ),
    ]
