# Generated by Django 4.0.3 on 2022-06-02 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_attendancesession_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 12, 2, 39, 637072, tzinfo=utc)),
        ),
    ]
