# Generated by Django 4.0.3 on 2022-07-26 15:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_attendancesession_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionStatus',
        ),
        migrations.DeleteModel(
            name='AttendanceSessionStatus',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='RecordTypes',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 15, 21, 42, 168658, tzinfo=utc)),
        ),
    ]
