# Generated by Django 4.0.3 on 2022-07-19 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_nodedevice_remove_stafftitle_unique_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionStatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceSessionStatus',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecordTypes',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('semester', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 15, 16, 22, 319570, tzinfo=utc)),
        ),
    ]
